# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 23:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseApp', '0001_initial'),
        ('loginApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='courses',
            field=models.ManyToManyField(related_name='users', to='courseApp.Course'),
        ),
    ]
